# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [45]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [46]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-9.5211e+21,  9.3046e-43,  1.6631e+00],
        [ 2.2467e+00,  2.6284e+00,  2.0963e+00],
        [ 2.9041e+00,  2.1244e+00,  2.2797e+00],
        [ 6.1976e-01,  9.7785e-01,  1.7196e-01],
        [ 1.7235e+00,  2.5588e-01,  1.3227e+00]])


Construct a randomly initialized matrix

In [47]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8830, 0.7305, 0.9080],
        [0.9638, 0.9266, 0.8115],
        [0.7248, 0.5449, 0.3061],
        [0.6250, 0.2291, 0.0614],
        [0.0259, 0.9459, 0.3089]])


Get its size

In [48]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [49]:
x[1:3] = 2
print(x)

tensor([[0.8830, 0.7305, 0.9080],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6250, 0.2291, 0.0614],
        [0.0259, 0.9459, 0.3089]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [50]:
print(torch.ones((2,17)).size())
a = torch.ones((3,1))
print(a.type())
print(a.dtype)
print(torch.get_default_dtype())
print(a.type(torch.float).type())
b = torch.full((5,2,1), 7)
print(b.type(torch.int64).type())
c = torch.zeros((5)).type(torch.uint8)
c[1:4] = 1
print(c)
print(c.type())
print(c.size())
type((5,))



torch.Size([2, 17])
torch.FloatTensor
torch.float32
torch.float32
torch.FloatTensor
torch.LongTensor
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)
torch.ByteTensor
torch.Size([5])


tuple

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [51]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1465, 1.6274, 1.0562],
        [2.2829, 2.4803, 2.7131],
        [2.7418, 2.4681, 2.6365],
        [1.0016, 0.4388, 0.2895],
        [0.5055, 1.1648, 1.0654]])


### 2.2 Addition: syntax 2

In [7]:
print(torch.add(x, y))

tensor([[0.9561, 0.1569, 1.6631],
        [2.2467, 2.6284, 2.0963],
        [2.9041, 2.1244, 2.2797],
        [0.6198, 0.9778, 0.1720],
        [1.7235, 0.2559, 1.3227]])


### 2.3 Addition: giving an output tensor

In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9561, 0.1569, 1.6631],
        [2.2467, 2.6284, 2.0963],
        [2.9041, 2.1244, 2.2797],
        [0.6198, 0.9778, 0.1720],
        [1.7235, 0.2559, 1.3227]])


### 2.4 Addition: in-place

adds `x` to `y`

In [9]:
y.add_(x)
print(y)

tensor([[0.9561, 0.1569, 1.6631],
        [2.2467, 2.6284, 2.0963],
        [2.9041, 2.1244, 2.2797],
        [0.6198, 0.9778, 0.1720],
        [1.7235, 0.2559, 1.3227]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [53]:
print(x[:, 1])

tensor([0.7305, 2.0000, 2.0000, 0.2291, 0.9459])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [56]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

x = torch.arange(5)
y = torch.arange(5)
print(torch.Tensor.mul(x,y))
print(torch.Tensor.div(x,y))
print(torch.Tensor.matmul(torch.arange(8).reshape(2,4), torch.arange(8).reshape(4,2)))


Using cuda device
tensor([ 0,  1,  4,  9, 16])
tensor([nan, 1., 1., 1., 1.])
tensor([[28, 34],
        [76, 98]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [12]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [13]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [57]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [60]:
a = torch.ones((5,2)).numpy()
print(type(a))
torch.from_numpy(a).type()


<class 'numpy.ndarray'>


'torch.FloatTensor'

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.0705, 0.0949, 0.9734],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1682, 0.5153, 0.1253],
        [0.7264, 0.1078, 0.7945]], device='cuda:0')
tensor([[0.9561, 0.1569, 1.6631],
        [2.2467, 2.6284, 2.0963],
        [2.9041, 2.1244, 2.2797],
        [0.6198, 0.9778, 0.1720],
        [1.7235, 0.2559, 1.3227]], device='cuda:0')
tensor([[1.0266, 0.2519, 2.6365],
        [4.2467, 4.6284, 4.0963],
        [4.9041, 4.1244, 4.2797],
        [0.7880, 1.4932, 0.2972],
        [2.4499, 0.3637, 2.1172]], device='cuda:0')
